In [25]:
#Writing to a file

my_file = open("Numbers.txt", "w")

my_file.write("3, 45, 83, 21")

my_file.close ()


In [26]:
#Reading from a file 

with open ("Numbers.txt", "r") as myfile:
    data = myfile.read().replace("\n",",")

myfile.close ()

print(data)

3, 45, 83, 21


In [27]:
#Appending a file

my_file = open("Numbers.txt", "a")

my_file.write(" Do you like these numbers?")

my_file.close()

In [11]:
#Write a program to ask a student for their percentage mark and convert this to a grade. The conversion will be done in a function called mark_grade.

for i in range(0,100):
    mark_grade = float(input("What is your percentage mark?"))

    if mark_grade > 0 and mark_grade < 50:
        print("Your Grade is an F")

    elif mark_grade >=50 and mark_grade <=60:
        print("Your Grade is a D")

    elif mark_grade > 60 and mark_grade <=70:
        print("Your Grade is a C")
    
    elif mark_grade > 70 and mark_grade <=80:
        print("Your Grade is a B")

    elif mark_grade > 80 and mark_grade <=90:
        print("Your Grade is an A")

    elif mark_grade > 90 and mark_grade <=100:
        print("Your Grade is an A*")

    else:
        print("Oh No, something went wrong. Did you type a percentage grade between 0 and 100?")


Your Grade is a D


ValueError: could not convert string to float: ''

In [ ]:
#Create a 1D array of numbers from 0 to 9

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

In [10]:
#Create a 3×3 NumPy array of all Boolean value Trues

import numpy as np

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
#Extract all odd numbers from array of 1-10

import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [37]:
#Replace all odd numbers in an array of 1-10 with the value -1

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[a%2 == 1] = -1

In [34]:
#Convert a 1D array to a 2D array with 2 rows

import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8])

arr_2d = np.reshape(arr, (2,4))

print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [91]:
#Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

import numpy as np

a = np.array([1, 5, 10])
b = np.array([2, 4, 8])

c= np.vstack((a,b))

print(c)

d = np.dot(a,b)
sum = np.sum(c)

print(sum)

[[ 1  5 10]
 [ 2  4  8]]
30


In [7]:
#Extension -  Create the following pattern without hardcoding. Use only NumPy functions.

import numpy as np 

a = np.array([1,2,3])

np.r_[(np.repeat(a,3), np.tile(a,3))]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
#Extension - In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b.

import numpy as np 

a = np.array = ([1,2,3,4,5])
b = np.array = ([4,5,6,7,8,9])

np.setdiff1d(b, a)


array([6, 7, 8, 9])